# Generated by Django 3.2.7 on 2021-10-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
