# Generated by Django 3.2.7 on 2021-10-15 10:33

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20211014_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='In progress', max_length=100, no_check_for_status=True),
        ),
    ]
