<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-10-12 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.7 on 2021-10-11 14:44

from django.db import migrations, models
>>>>>>> e6c35691a81bc41017155fd9eaac78025b720a2a


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> e6c35691a81bc41017155fd9eaac78025b720a2a
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
<<<<<<< HEAD
                ('specification', models.TextField()),
=======
                ('description', models.TextField()),
>>>>>>> e6c35691a81bc41017155fd9eaac78025b720a2a
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image')),
            ],
            options={
                'abstract': False,
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField()),
                ('rating', models.PositiveBigIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
=======
>>>>>>> e6c35691a81bc41017155fd9eaac78025b720a2a
    ]
